spring:
  application:
    name: passenger-service
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/postgres
    username: ${dbPassword:postgres}
    password: ${dbUsername:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  messages:
    basename: message-constants
springdoc:
  api-docs:
    path: /api/v1/passengers/docs
  swagger-ui:
    path: /api/v1/passengers/swagger-ui.html