spring:
  application:
    name: passenger-service
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/postgres
    username: ${dbPassword:postgres}
    password: ${dbUsername:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  messages:
    basename: message-constants

